### ISSUE TITLE
Cannot enter data into the timetable

### ISSUE THREAD

**Issue by EizEddin** [cwarwicker/moodle-block_elbp_timetable#2]
Hi,
Maybe this is an enquiry rather than an issue.
I cannot seem to find a way to add data to the timetable, not even from the main ELDP plugin.
So how is the timetable supposed to work?
Thanks.

**Comment by cwarwicker** [comment]
Hi,

The timetable works by drawing data in either from another database, using an MIS connection. Or by importing data into the plugin, using the Cron section.

The wiki should hopefully explain things: https://github.com/cwarwicker/moodle-block_elbp/wiki/2-Managing-Plugins#221-timetable
